### ISSUE TITLE
I can't get the package from composer for some reason?

### ISSUE THREAD

**Issue by ScooterSam** [SocialiteProviders/Twitch#5]
Class SocialiteProviders\Twitch\TwitchExtendSocialite does not exist, and yeah.. so i can't develop my app xD

**Comment by ScooterSam** [comment]
And also, laravel error:

InvalidArgumentException in Manager.php line 90:
Driver [twitch] not supported.

Everything is done properly, all other Socialite providers are working fine

**Comment by AndyWendt** [comment]
Nearly always when we see or hear about this error `driver not supported` it is because of a mis-configuration/setup.  

As for the other issue, I would try a `composer dumpautoload`.  I looked through the classes and they appear to be properly named and namespaced  

You will need to provide additional detail for further assistance.  If you do find something that is wrong, feel free to send a PR to help with open source.  We are all devs with full time jobs :smile:

**Comment by DraperStudio** [comment]
`composer require socialiteproviders/twitch` works fine, not finding any issues with that.
